### PR TITLE
Added types and JSON-LD support

### PR DESCRIPTION
**Pull request by ginnyTheCat**
This PR adds TypeScript types and JSON-LD support.

JSON-DL allows sites to show up as articles or show rankings in the search results.
https://developers.google.com/search/docs/data-types/article

### CODE REVIEW

**Comment by artiebits** [comment]
Hi @ginnyTheCat,

Thank you for your contribution. i will merge it to master, but I have 2 remarks:
1. There is a small typo in word `customisized`.
2. Consider updating tests. You can use [this spec file](https://github.com/garmeeh/next-seo/blob/master/cypress/e2e/jsonld.spec.js) as an example. This can be done in a separate PR, no problem.

**Comment by ginnyTheCat** [comment]
Thanks for the example. Made it much easier.

**Comment by ginnyTheCat** [comment]
I added `schema-dts` as a real dependency instead of a dev dependency. This allows for better TypeScript types when using JSON-LD. It won't make the bundle bigger because the [js file](https://unpkg.com/browse/schema-dts@0.8.2/schema.js) has no real content and types are not compiled/bundled.
It's no problem if you don't want that. I'll just revert it then.

**Comment by artiebits** [comment]
thanks again for adding JSON-LD, I've released a new version `1.2.0` with your changes

**Pull request merged**
