### PR TITLE
Warnings are displayed

### PR DESCRIPTION
**Pull request by kudadam**
There is a warning displayed if the length of characters in the title tag is below 50 characters or above 70 characters.
Isssue #26

### CODE REVIEW

**Comment by Glench** [comment]
It's not possible to make this a compiler warning instead of a runtime warning?

**Comment by kudadam** [comment]
> It's not possible to make this a compiler warning instead of a runtime warning?

Naa, I don't think so

**Comment by artiebits** [comment]
hi guys, sorry for the delay in response but I don't think it make sense to show this warnings in console. What if I have a perfect description for my page but it is 161 characters long? This warning would annoy me. And why did you commit your vscode settings?

**Comment by kudadam** [comment]
Ermm... sorry, didn't see that I commited the vscode settings.
Okay, i will just close this pull request

**Pull request closed without merging**
